version: '3.8'

services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        aptmirror: ${APT_MIRROR:-ftp.jaist.ac.jp/pub/Linux}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ..:/workspace:cached
      - cargo_registry:/home/vscode/.cargo/registry
    command: /bin/sh -c "while sleep 1000; do :; done"
    user: vscode
    environment:
      DISPLAY: :0
volumes:
  cargo_registry:
